spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: ala
    password: ala
    driver-class-name: org.postgresql.Driver
  mail:
    host: localhost
    port: 1025
    username: ala
    password: ala
    properties:
      mail:
        smtp:
          trust: '*'
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: yhwdxGYjqMr3qRBFFxF3l7si5Q9PfetGI1TD0t4sl06ksSdvyhgLss8YL066tJsZ
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    upload:
      photos-output-path: ./uploads